[package]
name = "pipeweaver-midi"
version = "0.1.0"
edition = "2024"

[dependencies]
pipeweaver-ipc = { git = "https://github.com/pipeweaver/pipeweaver", commit = "228bf6b" }
pipeweaver-shared = { git = "https://github.com/pipeweaver/pipeweaver", commit = "228bf6b" }
pipeweaver-websocket-client = { path = "../pipeweaver-websocket-client" }
tokio = { version = "1.52.1", features = ["rt", "rt-multi-thread", "macros", "signal"] }
midir = "0.11.0"
midi-msg = { version = "0.9.0", features = ["serde"] }
ulid = "1.2.1"
egui = "0.34.2"
eframe = "0.34.2"
winit = "0.30.13"
log = "0.4.29"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
serde_with = "3.19.0"
clap = { version = "4.6.1", features = ["derive"] }